SP.Web/Controllers/ReportController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SP.Core.Master;
using SP.Service.Models;
using SP.Service.Services;

namespace SP.Web.Controllers
{
    [Authorize]
    public class ReportController : Controller
    {
        private readonly IMasterService _masterService;
        private readonly ILogService _logService;
        private readonly IUserService _userService;

        public ReportController(IMasterService masterService, ILogService logService, IUserService userService)
        {
            _masterService = masterService;
            _logService = logService;
            _userService = userService;
        }

        public async Task<IActionResult> ActionReportAsync()
        {
            var users = await _userService.GetUserNameListAsync();
            var list = new SelectList(users, "Id", "Name").ToList();
            list.Insert(0, new SelectListItem("-- ВСЕ --", ""));
            ViewData["UserList"] = list;

            return View("ActionReport");
        }

        [HttpPost]
        public async Task<IActionResult> LoadActionList(int? user, DateTime? start, DateTime? end)
        {
            if (user == null && start == null && end == null)
            {
                var zeroItem = new ActionListItem{ Description = "Установите фильтры для отображения данных"};
                return Json(new { data = new[] { zeroItem } });
            }

            var list = await _logService.GetActionListAsync(user, start, end);
            return Json(new { data = list });
        }

        public async Task<IActionResult> BalanceReportAsync()
        {
            await LoadEssentialDictionaries();

            return View("BalanceReport");
        }

        [HttpPost]
        public async Task<IActionResult> LoadBalanceList(int? region, int? terr, int? station, int? group, int? nom, DateTime? start, DateTime? end)
        {
            if (region == null && terr == null && station == null && group == null && nom == null && start == null && end == null)
            {
                var zeroItem = new
                {
                    groupName = string.Empty,
                    nomenclatureName = "Установите фильтры для отображения данных",
                    stationNumber = string.Empty,
                    actionDate = (DateTime?)null,
                    quantity = (decimal?)null
                };
                return Json(new { data = new[] { zeroItem } });
            }

            var data = await _logService.GetBalanceListAsync(region, terr, station, group, nom, start, end);
            var list = data.Select(x => new
            {
                groupName = x.NomenclatureGroupName,
                nomenclatureName = x.NomenclatureName,
                stationNumber = x.StationNumber,
                actionDate = x.Date,
                quantity = x.Quantity
            });
            return Json(new { data = list });
        }

        public async Task<IActionResult> ExceedPlanReportAsync()
        {
            await LoadEssentialDictionaries();

            return View("ExceedPlanReport");
        }

        [HttpPost]
        public async Task<IActionResult> LoadExceedPlanList(int? region, int? terr, int? station, int? group, int? nom, DateTime? start, DateTime? end)
        {
            if (region == null && terr == null && station == null && group == null && nom == null && start == null && end == null)
            {
                var zeroItem = new
                {
                    groupName = string.Empty,
                    nomenclatureName = "Установите фильтры для отображения данных",
                    stationNumber = string.Empty,
                    actionDate = (DateTime?)null,
                    plan = (decimal?)null,
                    quantity = (decimal?)null
                };
                return Json(new { data = new[] { zeroItem } });
            }

            var data = await _logService.GetExceedPlanListAsync(region, terr, station, group, nom, start, end);
            var list = data.Select(x => new
            {
                groupName = x.NomenclatureGroupName,
                nomenclatureName = x.NomenclatureName,
                stationNumber = x.StationNumber,
                actionDate = x.Date,
                plan = x.Plan,
                quantity = x.Quantity
            });
            return Json(new { data = list });
        }

        public async Task<IActionResult> OrderReportAsync()
        {
            await LoadEssentialDictionaries();

            return View("OrderReport");
        }

        [HttpPost]
        public async Task<IActionResult> LoadOrderDetailList(int? region, int? terr, int? station, int? group, int? nom, DateTime? start, DateTime? end)
        {
            if (region == null && terr == null && station == null && group == null && nom == null && start == null && end == null)
            {
                var zeroItem = new
                {
                    groupName = string.Empty,
                    nomenclatureName = "Установите фильтры для отображения данных",
                    stationNumber = string.Empty,
                    actionDate = (DateTime?)null,
                    quantity = (decimal?)null,
                    orderNumber = (int?)null
                };
                return Json(new { data = new[] { zeroItem } });
            }

            var data = await _logService.GetOrderListAsync(region, terr, station, group, nom, start, end);
            var list = data.Select(x => new
            {
                groupName = x.NomenclatureGroupName,
                nomenclatureName = x.NomenclatureName,
                stationNumber = x.StationNumber,
                actionDate = x.Date,
                quantity = x.Quantity,
                orderNumber = x.OrderNumber
            });
            return Json(new { data = list });
        }

        public async Task<IActionResult> ChangeReportAsync()
        {
            var users = await _userService.GetUserNameListAsync();
            var list = new SelectList(users, "Id", "Name").ToList();
            list.Insert(0, new SelectListItem("-- ВСЕ --", ""));
            ViewData["UserList"] = list;

            return View("ChangeReport");
        }

        [HttpPost]
        public async Task<IActionResult> LoadChangeList(int? user, DateTime? start, DateTime? end)
        {
            if (user == null && start == null && end == null)
            {
                var zeroItem = new ChangeListItem { OldValue = "Установите фильтры для отображения данных" };
                return Json(new { data = new[] { zeroItem } });
            }

            var list = await _logService.GetChangeListAsync(user, start, end);
            return Json(new { data = list });
        }

        private async Task LoadEssentialDictionaries()
        {
            var regions = await _masterService.SelectRegionAsync();
            var list = new SelectList(regions, "Id", "Name").ToList();
            list.Insert(0, new SelectListItem("-- ВСЕ --", ""));
            ViewData["RegionList"] = list;

            var nomenclatureGroups = await _masterService.GetDictionaryListAsync<NomenclatureGroup>();
            var groupList = new SelectList(nomenclatureGroups, "Id", "Name").ToList();
            groupList.Insert(0, new SelectListItem("-- ВСЕ --", ""));
            ViewData["NomenclatureGroupList"] = groupList;
        }
    }
}

SP.Web/Controllers/StationController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SP.Core.Log;
using SP.Core.Master;
using SP.Data;
using SP.Service.Models;
using SP.Service.Services;
using SP.Web.Utility;

namespace SP.Web.Controllers
{
    [Authorize]
    public class StationController : Controller
    {
        private readonly INetObjectService _gasStationService;
        private readonly IMasterService _masterService;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IAppLogger _appLogger;

        public StationController(INetObjectService gasStationService, IMasterService masterService, UserManager<ApplicationUser> userManager, IAppLogger appLogger)
        {
            _gasStationService = gasStationService;
            _masterService = masterService;
            _userManager = userManager;
            _appLogger = appLogger;
        }

        #region Gas stations

        public async Task<IActionResult> Index(string regions, string terrs)
        {
            await _appLogger.SaveActionAsync(User.Identity.Name, DateTime.Now, "gasstation", "Открыт справочник АЗС.");
            var user = await _userManager.GetUserAsync(User);
            var currentRoles = await _userManager.GetRolesAsync(user);
            var person = await _masterService.GetPersonAsync(user.Id);

            var regionList = currentRoles.Contains("RegionalManager")
                ? await _masterService.SelectRegionAsync(person.Id)
                : await _masterService.SelectRegionAsync();

            var list = new SelectList(regionList, "Id", "Name").ToList();
            list.Add(new SelectListItem("ВСЕ", Int32.MaxValue.ToString()));
            ViewData["RegionList"] = list;
            ViewData["SelectedRegions"] = regions;
            ViewData["SelectedTerritories"] = terrs;

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoadList(string regions, string terrs, int objectType = 1)
        {
            if (!string.IsNullOrWhiteSpace(regions))
            {
                regions = null;
            }

            int[] regionIdList = regions.SplitToIntArray();
            int[] terrIdList = terrs.SplitToIntArray();

            var user = await _userManager.GetUserAsync(User);
            var currentRoles = await _userManager.GetRolesAsync(user);
            var person = await _masterService.GetPersonAsync(user.Id);
            int? personId = null;
            if (currentRoles.Contains("RegionalManager"))
            {
                personId = person.Id;
            }

            var stations = await GetGasStationListItems(regionIdList, terrIdList, personId);

            return Json(new { data = stations });
        }

        public async Task<IActionResult> LoadStations(string regions, string terrs, int objectType = 1)
        {
            int[] regionIdList = regions.SplitToIntArray();
            int[] terrIdList = terrs.SplitToIntArray();

            IEnumerable<DictionaryListItem> stations;
            var oejctTypeValue = (Core.Enum.ObjectType)objectType;
            switch (oejctTypeValue)
            {
                case Core.Enum.ObjectType.FuelBase:
                    var fuelBases = await GetFuelBaseListItems();
                    stations = fuelBases
                        .OrderBy(x => x.ObjectName)
                        .Select(x => new DictionaryListItem
                        {
                            Id = x.Id,
                            Name = x.ObjectName
                        });
                    break;
                case Core.Enum.ObjectType.Office:
                    var offices = await GetOfficeListItems();
                    stations = offices
                        .OrderBy(x => x.ObjectName)
                        .Select(x => new DictionaryListItem
                        {
                            Id = x.Id,
                            Name = x.ObjectName
                        });
                    break;
                case Core.Enum.ObjectType.Laboratory:
                    var laboratories = await GetLaboratoryListItems();
                    stations = laboratories
                        .OrderBy(x => x.ObjectName)
                        .Select(x => new DictionaryListItem
                        {
                            Id = x.Id,
                            Name = x.ObjectName
                        });
                    break;
                default:
                    var list = await GetGasStationListItems(regionIdList, terrIdList);
                    stations = list
                        .OrderBy(x => x.StationNumber)
                        .Select(x => new DictionaryListItem
                        {
                            Id = x.Id,
                            Name = x.StationNumber
                        });
                    break;
            }

            return Json(stations);
        }

        private async Task<IEnumerable<GasStationListItem>> GetGasStationListItems(int[] regions, int[] territories, int? personId = null)
        {
            IEnumerable<GasStationListItem> stations;
            if (regions == null && territories == null)
            {
                stations = new GasStationListItem[0];
            }
            else if (personId != null)
            {
                stations = await _gasStationService.GetGasStationListAsync(regions, territories, personId.Value);
            }
            else 
            {
                stations = await _gasStationService.GetGasStationListAsync(regions, territories);
            }

            return stations;
        }

        [Route("Station/{id}")]

        public async Task<IActionResult> GetAsync(int id, string regions, string terrs)
        {
            var station = await _gasStationService.GetGasStationAsync(id);
            if (station == null)
            {
                return NotFound();
            }

            await _appLogger.SaveActionAsync(User.Identity.Name, DateTime.Now, "gasstation",
                $"Открыта запись АЗС {station.StationNumber}");

            return await PrepareGasStationView(station, regions, terrs);
        }

        private async Task<IActionResult> PrepareGasStationView(GasStationModel model, string regions, string terrs)
        {
            var regionList = await _masterService.SelectRegionAsync();
            ViewData["RegionList"] = new SelectList(regionList, "Id", "Name");
            var territoryList = await _masterService.SelectTerritoryAsync(regions.SplitToIntArray());
            ViewData["TerritoryList"] = new SelectList(territoryList, "Id", "Name");
            var settlementList = await _masterService.GetDictionaryListAsync<Settlement>();
            ViewData["SettlementList"] = new SelectList(settlementList, "Id", "Name");
            var stationLocationList = await _masterService.GetDictionaryListAsync<StationLocation>();
            ViewData["StationLocationList"] = new SelectList(stationLocationList, "Id", "Name");
            var stationStatusList = await _masterService.GetDictionaryListAsync<StationStatus>();
            ViewData["StationStatusList"] = new SelectList(stationStatusList, "Id", "Name");
            var segmentList = await _masterService.GetDictionaryListAsync<Segment>();
            ViewData["SegmentList"] = new SelectList(segmentList, "Id", "Name");
            var serviceLevelList = await _masterService.GetDictionaryListAsync<ServiceLevel>();
            ViewData["ServiceLevelList"] = new SelectList(serviceLevelList, "Id", "Name");
            var operatorRoomFormatList = await _masterService.GetDictionaryListAsync<OperatorRoomFormat>();
            ViewData["OperatorRoomFormatList"] = new SelectList(operatorRoomFormatList, "Id", "Name");
            var managementSystemList = await _masterService.GetDictionaryListAsync<ManagementSystem>();
            ViewData["ManagementSystemList"] = new SelectList(managementSystemList, "Id", "Name");
            var tradingHallOperatingModeList = await _masterService.GetDictionaryListAsync<TradingHallOperatingMode>();
            ViewData["TradingHallOperatingModeList"] = new SelectList(tradingHallOperatingModeList, "Id", "Name");
            var clientRestroomList = await _masterService.GetDictionaryListAsync<ClientRestroom>();
            ViewData["ClientRestroomList"] = new SelectList(clientRestroomList, "Id", "Name");
            var cashboxLocationList = await _masterService.GetDictionaryListAsync<CashboxLocation>();
            ViewData["CashboxLocationList"] = new SelectList(cashboxLocationList, "Id", "Name");
            var tradingHallSizeList = await _masterService.GetDictionaryListAsync<TradingHallSize>();
            ViewData["TradingHallSizeList"] = new SelectList(tradingHallSizeList, "Id", "Name");
            var cashRegisterTapeList = await _masterService.GetDictionaryListAsync<CashRegisterTape>();
            ViewData["CashRegisterTapeList"] = new SelectList(cashRegisterTapeList, "Id", "Name");

            ViewData["SelectedRegions"] = regions;
            ViewData["SelectedTerritories"] = terrs;

            return View("GasStation", model);
        }

        [Route("Station/Create")]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> CreateAsync(string regions, string terrs)
        {
            var model = new GasStationModel();
            return await PrepareGasStationView(model, regions, terrs);
        }

        /// <summary>
        /// Сохранить АЗС и вернуться в список
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        [Authorize(Roles = "Administrator,RegionalManager")]

SP.Web/Views/Shared/_Layout.cshtml
@{
    bool isAdminRole = this.User.IsInRole("Administrator");
    bool isSupplyChief = this.User.IsInRole("SupplyChief");
    bool isSupplySpecialistRole = this.User.IsInRole("SupplySpecialist");
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Supply Planner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/chosen/chosen.css" />
        <link rel="stylesheet" href="~/bundles/dt.bundle.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/custom.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/chosen/chosen.min.css" />
        <link rel="stylesheet" href="~/bundles/dt.bundle.min.css" />
        <link rel="stylesheet" href="~/bundles/site.bundle.min.css" />
    </environment>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Планирование поставок ТМЦ</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    @{
                        if (this.User.Identity.IsAuthenticated)
                        {
                                        <ul class="navbar-nav flex-grow-1">
                                            @if (isAdminRole || isSupplySpecialistRole || isSupplyChief)
                                            {
                                                <li class="nav-item">
                                                    <div class="dropdown">
                                                        <span class="nav-link text-dark dropbtn">Плановая поставка</span>
                                                        <div class="dropdown-content">
                                                            <a class="nav-link text-dark" asp-area="" asp-controller="Inventory" asp-action="FixedDemand">Плановая поставка</a>
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="Order">Список заказов</a>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="nav-item">
                                                    <div class="dropdown">
                                                        <span class="nav-link text-dark dropbtn">Заказ</span>
                                                        <div class="dropdown-content">
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="Upload">Загрузка остатков ТМЦ</a>
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="AutoMerge">Автоматическое объединение ТМЦ с Номенклатурой</a>
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="ManualMerge">Ручное объединение ТМЦ с Номенклатурой</a>
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="Demand">Заказ ТМЦ</a>
                                                            <a class="nav-link text-dark" asp-controller="Inventory" asp-action="Order">Список заказов</a>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-area="" asp-controller="Nomenclature" asp-action="Index">Номенклатура</a>
                                                </li>
                                            }
                                            <li class="nav-item">
                                                <div class="dropdown">
                                                    <span class="nav-link text-dark dropbtn">Реестры объектов</span>
                                                    <div class="dropdown-content">
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Index">АЗС</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="FuelBase">Нефтебазы</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Office">Офисы</a>
                                                        <a class="nav-link text-dark" asp-area="" asp-controller="Station" asp-action="Laboratory">Лаборатории</a>
                                                    </div>
                                                </div>
                                            </li>
                                            @if (isAdminRole)
                                            {
                                                <li class="nav-item">
                                                    <div class="dropdown">
                                                        <span class="nav-link text-dark dropbtn">Справочники</span>
                                                        <div class="dropdown-content">
                                                            <a class="nav-link text-dark" asp-controller="Region" asp-action="Region">Регионы</a>
                                                            <a class="nav-link text-dark" asp-controller="Settlement" asp-action="Index">Населенный пункт</a>
                                                            <a class="nav-link text-dark" asp-controller="NomenclatureGroup" asp-action="Index">Группы номенклатуры</a>
                                                            <a class="nav-link text-dark" asp-controller="ObjectTypeNomenclatureGroup" asp-action="Index">Группы номенклатуры по типам объектов</a>
                                                            <a class="nav-link text-dark" asp-controller="StationLocation" asp-action="Index">Месторасположение</a>
                                                            <a class="nav-link text-dark" asp-controller="StationStatus" asp-action="Index">Статус</a>
                                                            <a class="nav-link text-dark" asp-controller="Segment" asp-action="Index">Сегмент</a>
                                                            <a class="nav-link text-dark" asp-controller="ServiceLevel" asp-action="Index">Кластер (уровень сервиса)</a>
                                                            <a class="nav-link text-dark" asp-controller="OperatorRoomFormat" asp-action="Index">Формат операторной</a>
                                                            <a class="nav-link text-dark" asp-controller="ManagementSystem" asp-action="Index">Режим работы торгового зала</a>
                                                            <a class="nav-link text-dark" asp-controller="TradingHallOperatingMode" asp-action="Index">Месторасположение</a>
                                                            <a class="nav-link text-dark" asp-controller="ClientRestroom" asp-action="Index">Санузел для клиентов</a>
                                                            <a class="nav-link text-dark" asp-controller="CashboxLocation" asp-action="Index">Расчетно-кассовый узел</a>
                                                            <a class="nav-link text-dark" asp-controller="TradingHallSize" asp-action="Index">Размер торгового зала</a>
                                                            <a class="nav-link text-dark" asp-controller="MeasureUnit" asp-action="Index">Единицы измерения</a>
                                                            <a class="nav-link text-dark" asp-controller="CashRegisterTape" asp-action="Index">Вид термоленты</a>
                                                        </div>
                                                    </div>
                                                </li>
                                                <li class="nav-item">
                                                    <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Пользователи</a>
                                                </li>
                                            }
                                            @if (isAdminRole || isSupplySpecialistRole || isSupplyChief)
                                            {
                                                <li class="nav-item">
                                                    <div class="dropdown">
                                                        <span class="nav-link text-dark dropbtn">Отчеты</span>
                                                        <div class="dropdown-content">
                                                            @if (isAdminRole || isSupplyChief)
                                                            {
                                                                <a class="nav-link text-dark" asp-controller="Report" asp-action="ActionReport">Отчет руководителя</a>
                                                            }
                                                            <a class="nav-link text-dark" asp-controller="Report" asp-action="BalanceReport">Контроль движения ТМЦ более 12 месяцев</a>
                                                            <a class="nav-link text-dark" asp-controller="Report" asp-action="ExceedPlanReport">Контроль соблюдения норм</a>
                                                            <a class="nav-link text-dark" asp-controller="Report" asp-action="OrderReport">Отчет по отгрузке</a>
                                                            <a class="nav-link text-dark" asp-controller="Report" asp-action="ChangeReport">Отчет по изменениям</a>
                                                        </div>
                                                    </div>
                                                </li>
                                            }
                                        </ul>
                        }
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - 2024
        </div>
    </footer>

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <environment include="Development">
        <script src="~/lib/chosen/chosen.jquery.js"></script>
        <script src="~/bundles/dt.bundle.js"></script>
        <script src="~/bundles/site.bundle.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/chosen/chosen.jquery.min.js"></script>
        <script src="~/bundles/dt.bundle.min.js"></script>
        <script src="~/bundles/site.bundle.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)
</body>
</html>

SP.Web/Views/Shared/_MasterDictionaryEdit.cshtml
@model SP.Service.Models.DictionaryModel
@{
    Layout = null;
    bool isAdminRole = this.User.IsInRole("Administrator");
}

<form id="EditForm">
    <div class="modal-header">
        <h5 class="modal-title">@ViewData["Title"]</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
    </div>
    <div class="modal-body">
        <input asp-for="Id" type="hidden" />
        <div class="form-group">
            <label asp-for="Name" class="control-label"></label>
            <input asp-for="Name" class="form-control" />
        </div>
        <div class="form-group form-check">
            <label class="form-check-label">
                <input class="form-check-input" asp-for="Inactive" /> @Html.DisplayNameFor(model => model.Inactive)
            </label>
        </div>
        <div id="EditAlert" class="text-danger"></div>
    </div>
    <div class="modal-footer form-row button-row">
        @if (isAdminRole)
        {
            <button type="button" class="btn btn-primary" onclick="postForm();">Сохранить и закрыть</button>
        }
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
    </div>
</form>

<script>
    function postForm() {
        var url = '/@ViewData["ClassName"]/Edit';
        var postData = $('#EditForm').serialize();
        $.post(url, postData, function (data) {
            if (isNaN(data)) {
                $('#EditAlert').html(data);
                return;
            }
            $('#DictionaryGrid').DataTable().ajax.reload(null, false);
            $('#DictionaryModal').modal('hide');
        });
    }
</script>